# Generated by Django 5.1.4 on 2025-05-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(default='fix this'),
            preserve_default=False,
        ),
    ]
