# Generated by Django 5.1.4 on 2025-07-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_urls',
            field=models.TextField(blank=True),
        ),
    ]
