# Generated by Django 5.1.4 on 2025-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_code_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
