# Generated by Django 5.1.4 on 2025-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_code_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
