# Generated by Django 5.1.4 on 2025-07-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
