# Generated by Django 5.1.4 on 2025-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_video',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demo_video',
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
