# Generated by Django 5.1.4 on 2025-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_project_code_video_remove_project_demo_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='youtube_URL',
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
