# Generated by Django 5.1.4 on 2025-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_project_youtube_url_project_youtube_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='youtube_ID',
            new_name='demo_ID',
        ),
        migrations.AddField(
            model_name='project',
            name='code_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
