# Generated by Django 5.1.4 on 2025-07-24 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_youtube_id_project_demo_id_project_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_ID',
        ),
        migrations.CreateModel(
            name='DesignConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_concepts', to='main.project')),
            ],
        ),
    ]
