# Generated by Django 5.1.4 on 2025-07-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_project_code_id_designconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reflection',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='reflection_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
