# Generated by Django 5.1.4 on 2025-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_project_reflection_project_reflection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_pic', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('welcome_message', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('about_message', models.TextField()),
            ],
        ),
    ]
