# Generated by Django 5.1.4 on 2025-08-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homecontents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='description',
            new_name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='leetcode_video',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='walkthrough_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='walkthrough_video_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
