# Generated by Django 5.1.4 on 2025-08-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_description_algorithm_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='algorithm_images/'),
        ),
    ]
