# Generated by Django 5.1.4 on 2025-10-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_algorithm_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontents',
            name='resume_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
    ]
