# Generated by Django 5.1.4 on 2025-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_homecontents_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontents',
            name='resume_image',
            field=models.FileField(blank=True, null=True, upload_to='home_images/'),
        ),
    ]
