# Generated by Django 5.1.4 on 2025-10-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_homecontents_resume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontents',
            name='github',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecontents',
            name='linkedIn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
